// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $notes_index from "./routes/notes/index.tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $FeaturedBlogPosts from "./islands/FeaturedBlogPosts.tsx";
import * as $FeaturedProjects from "./islands/FeaturedProjects.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $StatusUpdate from "./islands/StatusUpdate.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/notes/index.tsx": $notes_index,
    "./routes/projects/index.tsx": $projects_index,
  },
  islands: {
    "./islands/FeaturedBlogPosts.tsx": $FeaturedBlogPosts,
    "./islands/FeaturedProjects.tsx": $FeaturedProjects,
    "./islands/Hero.tsx": $Hero,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/StatusUpdate.tsx": $StatusUpdate,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
